dmb_delay_systick: Functions
Functions
Dmb_delay_systick
Functions
void dmb_delay_systick_init (uint32_t clock_speed)
Inicjalizuje Systick na przerwanie co 1ms.
void dmb_delay_systick_register_callback (dmb_delay_systick_callback_t user_callback)
Rejestracja callbacka, ktory wykonuje sie co wywolanie timera. Mozemy tez wpisac NULL/0 zeby wylaczyc callback.
void _delay_ms (uint32_t delay)
Podstawowa funkcja delaya oczekujacego zadana ilosc milisekund. Delay moze byc mniejszy o 1ms niz podany.
uint32_t systick_get_system_uptime ()
Pobranie czasu dzialania urzadzenia w milisekundach. Przepelnia sie po ~49dniach.
void systick_set_timeout (uint32_t timeout)
Ustawienie punktu od ktorego bedzie zliczany timeout. Zastosowanie np w komunikacji I2C.
uint8_t systick_check_timeout ()
Sprawdzenie timeoutu. Zwraca 0 jesli minal juz timeout.
void SysTick_Handler (void)
Obsluga przerwania od timera SysTick.
Detailed Description
Function Documentation
_delay_ms()
void _delay_ms (uint32_t delay)
Podstawowa funkcja delaya oczekujacego zadana ilosc milisekund. Delay moze byc mniejszy o 1ms niz podany.
Attention
Blokujaca!
Parameters
delay czas w milisekundach
Definition at line 114 of file dmb_delay_systick.c.
References delay_counter.
 {
   delay_counter = delay;
   while( delay_counter )
   {
 #if DMB_SYSTICK_ENABLE_WFI
     __WFI(); // delikatne uspienie urzadzenia
 #endif
   }
 }
dmb_delay_systick_init()
void dmb_delay_systick_init (uint32_t clock_speed)
Inicjalizuje Systick na przerwanie co 1ms.
Parameters
clock_speed clock_speed predkosc taktowania timera SysTick
Definition at line 88 of file dmb_delay_systick.c.
References DMB_SYSTICK_INTERRUPT_PRIORITY.
 {
   SysTick_Config( clock_speed / 1000 );
   NVIC_SetPriority( SysTick_IRQn, DMB_SYSTICK_INTERRUPT_PRIORITY );
 }
dmb_delay_systick_register_callback()
void dmb_delay_systick_register_callback (dmb_delay_systick_callback_t user_callback)
Rejestracja callbacka, ktory wykonuje sie co wywolanie timera. Mozemy tez wpisac NULL/0 zeby wylaczyc callback.
Attention
Uruchamiany jest na poziomie przerwania!
Parameters
user_callback callback do uruchamiania
Definition at line 102 of file dmb_delay_systick.c.
References callback.
 {
   callback = user_callback;
 }
systick_check_timeout()
uint8_t systick_check_timeout ()
Sprawdzenie timeoutu. Zwraca 0 jesli minal juz timeout.
Returns
0: Timeout minal
1: Timeout jeszcze nie minal
Definition at line 151 of file dmb_delay_systick.c.
References timeout_counter.
 {
   if(timeout_counter > 0)
   {
     return 1;
   }
   return 0;
 }
systick_get_system_uptime()
uint32_t systick_get_system_uptime ()
Pobranie czasu dzialania urzadzenia w milisekundach. Przepelnia sie po ~49dniach.
Returns
Definition at line 129 of file dmb_delay_systick.c.
References system_up_time.
 {
   return system_up_time;
 }
SysTick_Handler()
void SysTick_Handler (void)
Obsluga przerwania od timera SysTick.
Definition at line 163 of file dmb_delay_systick.c.
References call_callback(), decrement_delay_counter(), decrement_timeout_counter(), and increment_system_up_time().
 {
   increment_system_up_time();
   decrement_delay_counter();
   decrement_timeout_counter();
   call_callback();
 }
systick_set_timeout()
void systick_set_timeout (uint32_t timeout)
Ustawienie punktu od ktorego bedzie zliczany timeout. Zastosowanie np w komunikacji I2C.
Parameters
timeout czas timeoutu
Definition at line 139 of file dmb_delay_systick.c.
References timeout_counter.
 {
   timeout_counter = timeout;
 }